# -*- coding: utf-8 -*-

class Config:
    
    DEFAULT_TIMEOUT = 30
    VIDEO_SIZE_CHECK_TIMEOUT = 10
    IMAGE_DOWNLOAD_TIMEOUT = 30
    VIDEO_DOWNLOAD_TIMEOUT = 300
    
    DEFAULT_LARGE_VIDEO_THRESHOLD_MB = 50.0
    MAX_LARGE_VIDEO_THRESHOLD_MB = 100.0
    
    DEBUG_MODE = False

